name: alquran
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  get: 4.6.6
  http: 1.2.0
  lottie: ^3.0.0
  just_audio: ^0.9.36
  sqflite: 2.3.2
  path_provider: 2.1.2
  scroll_to_index: 3.0.1
  flutter: 
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
    - assets/fonts/
  fonts: 
    - family: Arab
      fonts: 
        - asset: assets/fonts/arab.ttf
    - family: ArabKedua
      fonts: 
        - asset: assets/fonts/arabkedua.ttf
    - family: Misbah
      fonts: 
        - asset: assets/fonts/misbah.ttf
    - family: Qalam
      fonts: 
        - asset: assets/fonts/qalam.ttf
    - family: Mushaf
      fonts: 
        - asset: assets/fonts/mushaf.ttf
  uses-material-design: true

